### ISSUE TITLE
V2/hybrid torrent support

### ISSUE THREAD

**Issue by qu1ck** [ttlajus/lava_torrent#12]
Docs mention that it may be supported if there is demand.
Well, this is me, asking for this feature :)

**Comment by ttlajus** [comment]
Actually I said "enough demand" and I was talking about merkle tree torrents :)

From the doc:

> [Merkle tree torrents](http://bittorrent.org/beps/bep_0030.html) can be supported if there’s enough demand. [v2](http://bittorrent.org/beps/bep_0052.html) torrents might be supported once it’s stabilized.

You are the first one to ask in 5 years. I believe v2 torrents are not common in the wild and the spec is still not stabilized. Why don't you briefly explain your use case?

**Comment by ttlajus** [comment]
Thanks for the explanation.

Frankly it doesn't sound like having v2 support is critical at this point, so it will be pretty low on my todo list.

I can still do it, but it will take a while. Don't expect a quick turnaround.

In the mean time I suggest that you explore other options (e.g. `libtorrent` with bindgen).

**Comment by qu1ck** [comment]
I need my code to be cross platform (mac/win/linux) so things like cpp libs with bindings can get hairy quick as they are usually not hermetic.

> I can still do it, but it will take a while. Don't expect a quick turnaround.

Perfectly fine by me, thanks for this lib and being responsive.

**Comment by ttlajus** [comment]
After making an attempt, I've decided to reverse my decision and give up. It's just too boring for me. Sorry.

Additionally I've placed this lib in maintenance mode (see README). It's been 5 yrs, and I think it's time for me to throw in the towel.

You can still use this lib for hybrid torrents if you want. Your statement

> I checked that your library still parses hybrid torrents but (as expected) only v1 info.

is not entirely accurate. `piece layers` and `file tree` are in `Torrent.extra_fields` and `Torrent.extra_info_fields` respectively. You'll have to interpret the bencode items yourself, so not super convenient, but they are there.

**Comment by qu1ck** [comment]
Fair enough, thanks for transparency.
