### ISSUE TITLE
Torrent building progress callbacks

### ISSUE THREAD

**Issue by qu1ck** [ttlajus/lava_torrent#13]
Since hashing large torrent can take a while it would be nice to have a way to pass callback to build() which will periodically report back with processed bytes/total and processed files/total. 

Callback return can be used to interrupt the process.

This is useful to show a progress bar in UI and process a cancel request.

**Comment by ttlajus** [comment]
Added in `v0.11.0`.

It's not exactly the same as what you described, but [`TorrentBuilder::build_non_blocking()`](https://docs.rs/lava_torrent/0.11.0/lava_torrent/torrent/v1/struct.TorrentBuilder.html#method.build_non_blocking) should do.

**Comment by qu1ck** [comment]
Thanks. It would be nice if number_of_pieces_processed / number_of_pieces_total were exposed too in addition to the integer percentage.

**Comment by ttlajus** [comment]
I will add it in the next release. They were not exposed because there's a caveat regarding `number_of_pieces_total` - it can be 0 initially, so not as straightforward as an integer indicator.

Also, since you are using these for a torrent client, maybe think about if the users really need/want such info in the interface. Something like `237.1k / 1.5m` is not as intuitive as `15%`.

**Comment by qu1ck** [comment]
Oh, I understand, it's just having only a percentage is limiting.

I would like to show:
1st stage: "Calculating number of pieces" (while Option<number_of_pieces_total> is None for example)
2nd stage: "Hashing pieces: x.x% ( processed / total )"
3rd stage: "Generating output"

I frequently deal with torrents of hundreds of GB so more detailed progress is useful to me.

**Comment by ttlajus** [comment]
It's fair that _you_ want this info. My point was that from a design point of view, it's unnecessary information overload. Indeed neither transmission nor qbittorrent does this. Of course it's your code and your decision. Just a comment :)

**Comment by qu1ck** [comment]
So we both agree that low level libs shouldn't be the limiting factor, they should provide all available information and the decision of how to present that to the user should be in the UI/app layer.

**Comment by ttlajus** [comment]
Getters have been added in `v0.11.1`.
