### ISSUE TITLE
What does it mean "maintenance mode"?

### ISSUE THREAD

**Issue by josecelano** [ttlajus/lava_torrent#15]
Are you planning to archive it? Make big changes? Is it paused?

I guess you only want to fix bugs for current users but you do not want to continue developing the package. I only want to know if it's a temporary state or definitive.

**Comment by ttlajus** [comment]
Hi, as noted in the README:

> NOTE: lava_torrent is now in maintenance mode. Bugs will still be fixed, but no new features will be released. If you need something, feel free to fork.

So your guess is correct. I do not see this changing in the foreseeable future, so you can say it's permanent.

The library currently can handle v1 torrents just fine, and it's fairly optimized in terms of hashing. If you need more, you'll have to find another crate or do it yourself.
