### ISSUE TITLE
Remove path component restrictions?

### ISSUE THREAD

**Issue by fgaz** [ttlajus/lava_torrent#3]
There are a couple of restrictions on the source path that as far as I can see do not map to restrictions in the torrent format, since the source path does not get in there:

https://github.com/ttlajus/lava_torrent/blob/30a527ecd77b5d254a72fe694961c425ae693ebc/src/torrent/v1/build.rs#L312-L330

Would you be fine with removing them? As an example, they would be causing trouble for a program that creates torrents in a hidden cache or data directory.

**Comment by ttlajus** [comment]
Hey there,

Are you saying you want to create torrents that contain hidden dirs/files? In the [doc](https://docs.rs/lava_torrent/0.5.0/lava_torrent/torrent/v1/struct.TorrentBuilder.html) I made a note about this. And from that note

> Clients like Deluge and qBittorrent also ignore hidden entries.

I wonder what your use case is that you need something the mainstream torrent clients don't support.

**Comment by fgaz** [comment]
Not exactly, the restriction in this library is stricter than that.

Let's say I want to create a torrent for the file `image.png` that is present in the directory `/home/me/.cache/foo/`.
I call `TorrentBuilder::new("/home/me/.cache/foo/image.png", 1048576)`, so that the torrent will only contain `image.png`.
But `.build()` will complain that `.cache` is in the path, even though that path component won't get in the torrent!

**Comment by fgaz** [comment]
> But hidden sub-dirs/files will continue to be ignored

sounds good! indeed my use case does not need hidden files _inside_ the torrent

> the validation on `..` stays

I'd remove that too since it also doesn't affect the torrent, but one can just normalize the path before feeding it to lava_torrent, so either way is fine

**Comment by ttlajus** [comment]
> I'd remove that too since it also doesn't affect the torrent

I try to lean on the defensive side, but let me think about that.

-----

I will deal with this and your PR this weekend. Thank you for your patience :)

**Comment by ttlajus** [comment]
Fixed in ad6b93ea4d8635851ebefa1ca4a2657beb09d45d.
`v0.6.0` has been [published](https://crates.io/crates/lava_torrent/versions).
Thank again @fgaz :+1:

**Comment by fgaz** [comment]
Great! Thanks a lot!
