### ISSUE TITLE
can the examples be more details

### ISSUE THREAD

**Issue by githik999** [ttlajus/lava_torrent#6]
first of all great work! 

i have been trying a lot of bencode crates and found this crate finally (in a very back end of search result in crates.io with keyword bencode)

this crate should be more in front in the crates.io search results

add more details to the examples would be perfect

such as showing how to use BencodeElem::from_bytes 

how to interact with the krpc protocol etc

more intact examples including dependencies and fn main 

just a small advise and many thanks for your incredible work

**Comment by ttlajus** [comment]
Hi there, thanks for your comments and kind words!

> this crate should be more in front in the crates.io search results

`lava_torrent` is primarily a library for interacting with `.torrent` files, so it's not surprising that it's ranked low if you search for "bencode". Yes, it can also interact with bencode, but that's more of a byproduct of the design.

> add more details to the examples would be perfect
> such as showing how to use BencodeElem::from_bytes

I will update README and doc when I get a chance.

> how to interact with the krpc protocol etc
> more intact examples including dependencies and fn main

That is out of scope for `lava_torrent`. The users are more than welcome to use it for `krpc`, but I have no intention (or time) to "officially" support that use case. So unfortunately I'll have to say no to this one.

**Comment by githik999** [comment]
thanks man! up thumb for you
